<?php

namespace App\Services\Address;

/**
 *
 */
class StreetTypeMapper
{
    /**
     *
     */
    CONST STREET_TYPES  = [
        "ACCS" => "ACCESS",
        "ALLY" => "ALLEY",
        "ALWY" => "ALLEYWAY",
        "AMBL" => "AMBLE",
        "ANCG" => "ANCHORAGE",
        "APP" => "APPROACH",
        "ARC" => "ARCADE",
        "ART" => "ARTERY",
        "AVE" => "AVENUE",
        "BASN" => "BASIN",
        "BCH" => "BEACH",
        "BDGE" => "BRIDGE",
        "BDWY" => "BROADWAY",
        "BEND" => "BEND",
        "BLK" => "BLOCK",
        "BRAE" => "BRAE",
        "BRCE" => "BRACE",
        "BRK" => "BREAK",
        "BROW" => "BROW",
        "BVD" => "BOULEVARD",
        "BYPA" => "BYPASS",
        "BYWY" => "BYWAY",
        "CAUS" => "CAUSEWAY",
        "CCT" => "CIRCUIT",
        "CDS" => "CUL-DE-SAC",
        "CH" => "CHASE",
        "CIR" => "CIRCLE",
        "CL" => "CLOSE",
        "CLDE" => "COLONNADE",
        "CLT" => "CIRCLET",
        "CMMN" => "COMMON",
        "CNR" => "CORNER",
        "CNWY" => "CENTREWAY",
        "CON" => "CONCOURSE",
        "COVE" => "COVE",
        "COWY" => "CROSSWAY",
        "CPS" => "COPSE",
        "CRCS" => "CIRCUS",
        "CRD" => "CROSSROAD",
        "CRES" => "CRESCENT",
        "CRSG" => "CROSSING",
        "CRSS" => "CROSS",
        "CRST" => "CREST",
        "CSO" => "CORSO",
        "CT" => "COURT",
        "CTR" => "CENTRE",
        "CTTG" => "CUTTING",
        "CTYD" => "COURTYARD",
        "CUWY" => "CRUISEWAY",
        "DALE" => "DALE",
        "DELL" => "DELL",
        "DEVN" => "DEVIATION",
        "DIP" => "DIP",
        "DR" => "DRIVE",
        "DRWY" => "DRIVEWAY",
        "DSTR" => "DISTRIBUTOR",
        "EDGE" => "EDGE",
        "ELB" => "ELBOW",
        "END" => "END",
        "ENT" => "ENTRANCE",
        "ESP" => "ESPLANADE",
        "EST" => "ESTATE",
        "EXP" => "EXPRESSWAY",
        "EXTN" => "EXTENSION",
        "FAWY" => "FAIRWAY",
        "FITR" => "FIRETRAIL",
        "FLAT" => "FLAT",
        "FOLW" => "FOLLOW",
        "FORM" => "FORMATION",
        "FRNT" => "FRONT",
        "FRTG" => "FRONTAGE",
        "FSHR" => "FORESHORE",
        "FTRK" => "FIRE TRACK",
        "FTWY" => "FOOTWAY",
        "FWY" => "FREEWAY",
        "GAP" => "GAP",
        "GDN" => "GARDEN",
        "GDNS" => "GARDENS",
        "GLD" => "GLADE",
        "GLEN" => "GLEN",
        "GLY" => "GULLY",
        "GR" => "GROVE",
        "GRA" => "GRANGE",
        "GRN" => "GREEN",
        "GRND" => "GROUND",
        "GTE" => "GATE",
        "GTES" => "GATES",
        "HILL" => "HILL",
        "HRD" => "HIGHROAD",
        "HTS" => "HEIGHTS",
        "HWY" => "HIGHWAY",
        "INTG" => "INTERCHANGE",
        "INTN" => "INTERSECTION",
        "JNC" => "JUNCTION",
        "KEY" => "KEY",
        "LANE" => "LANE",
        "LDG" => "LANDING",
        "LEES" => "LEES",
        "LINE" => "LINE",
        "LINK" => "LINK",
        "LKT" => "LOOKOUT",
        "LNWY" => "LANEWAY",
        "LOOP" => "LOOP",
        "LT" => "LITTLE",
        "LWR" => "LOWER",
        "MALL" => "MALL",
        "MEW" => "MEW",
        "MEWS" => "MEWS",
        "MNDR" => "MEANDER",
        "MT" => "MOUNT",
        "MWY" => "MOTORWAY",
        "NOOK" => "NOOK",
        "OTLK" => "OUTLOOK",
        "PARK" => "PARK",
        "PART" => "PART",
        "PASS" => "PASS",
        "PATH" => "PATH",
        "PDE" => "PARADE",
        "PHWY" => "PATHWAY",
        "PIAZ" => "PIAZZA",
        "PKLD" => "PARKLANDS",
        "PKT" => "POCKET",
        "PKWY" => "PARKWAY",
        "PL" => "PLACE",
        "PLAT" => "PLATEAU",
        "PLZA" => "PLAZA",
        "PNT" => "POINT",
        "PORT" => "PORT",
        "PROM" => "PROMENADE",
        "PSGE" => "PASSAGE",
        "QDGL" => "QUADRANGLE",
        "QDRT" => "QUADRANT",
        "QUAD" => "QUAD",
        "QY" => "QUAY",
        "QYS" => "QUAYS",
        "RAMP" => "RAMP",
        "RCH" => "REACH",
        "RD" => "ROAD",
        "RDGE" => "RIDGE",
        "RDS" => "ROADS",
        "RDSD" => "ROADSIDE",
        "RDWY" => "ROADWAY",
        "RES" => "RESERVE",
        "REST" => "REST",
        "RGWY" => "RIDGEWAY",
        "RIDE" => "RIDE",
        "RING" => "RING",
        "RISE" => "RISE",
        "RMBL" => "RAMBLE",
        "RND" => "ROUND",
        "RNDE" => "RONDE",
        "RNGE" => "RANGE",
        "ROW" => "ROW",
        "ROWY" => "RIGHT OF WAY",
        "RSBL" => "ROSEBOWL",
        "RTE" => "ROUTE",
        "RTT" => "RETREAT",
        "RTY" => "ROTARY",
        "RUE" => "RUE",
        "RUN" => "RUN",
        "RVR" => "RIVER",
        "RVRA" => "RIVIERA",
        "RVWY" => "RIVERWAY",
        "SBWY" => "SUBWAY",
        "SDNG" => "SIDING",
        "SHWY" => "STATE HIGHWAY",
        "SLPE" => "SLOPE",
        "SND" => "SOUND",
        "SPUR" => "SPUR",
        "SQ" => "SQUARE",
        "ST" => "STREET",
        "STPS" => "STEPS",
        "STRA" => "STRAND",
        "STRP" => "STRIP",
        "STRS" => "STAIRS",
        "SWY" => "SERVICE WAY",
        "TARN" => "TARN",
        "TCE" => "TERRACE",
        "THOR" => "THOROUGHFARE",
        "TKWY" => "TRUNKWAY",
        "TLWY" => "TOLLWAY",
        "TOP" => "TOP",
        "TOR" => "TOR",
        "TRI" => "TRIANGLE",
        "TRK" => "TRACK",
        "TRL" => "TRAIL",
        "TRLR" => "TRAILER",
        "TURN" => "TURN",
        "TWRS" => "TOWERS",
        "UPAS" => "UNDERPASS",
        "UPR" => "UPPER",
        "VALE" => "VALE",
        "VDCT" => "VIADUCT",
        "VIEW" => "VIEW",
        "VLLS" => "VILLAS",
        "VSTA" => "VISTA",
        "WADE" => "WADE",
        "WALK" => "WALK",
        "WAY" => "WAY",
        "WHRF" => "WHARF",
        "WKWY" => "WALKWAY",
        "WYND" => "WYND",
        "YARD"=> "YARD",
    ];

    /**
     * @param string|null $type
     * @return string|null
     */
    public static function getFullForm(?string $type): ?string
    {
        if ($type) {
            return self::STREET_TYPES[strtoupper($type)] ?? null;
        }
        return null;
    }

    /**
     * @param string|null $type
     * @return string|null
     */
    public static function  getShortForm(?string $type): ?string
    {
        if ($type) {
            return array_search(strtoupper($type), self::STREET_TYPES);
        }
        return null;
    }
}
